export const classes = {
  p: {
    mediumPaleP: "medium pale",
    mediumPaleHoverP: "medium pale hover",
    mediumGrowP: "medium grow",
    mediumWhiteP: "medium white",
    mediumPlaceholderP: "medium placeholder",
    regularDarkP: "regular dark",
    regularWhiteP: "regular white",
    regularHoverP: "regular hover",
    capitalisedP: " capitalised",
    largeP: "large",
    subtitleP: "subtitle",
  },
  h: {
    topTitleH1: "top-title",
    upperBlueH5: "upper blue",
    upperWhiteH5: "upper white",
    upperGrayH5: "upper gray",
    listsDarkH6: "lists dark",
    listWhiteH6: "listd white",
    cardH6: "card",
    quoteLargeH3: "quote large",
    quoteMediumH3: "quote medium",
    withHoverH4: "with-hover",
    smallH6: "small",
    normalH3: "normal",
    sectionWhiteH2: "section white",
    sectionDarkH2: "section dark",
  },
};
