export const pageViewVariants: any = {
  intro: {
    paddingTop: "1.5rem",
    paddingBottom: "4.5rem",
    contentMargin: "1.5rem 0 0 0",
    tablet: {
      paddingTop: "12.4rem",
      paddingBottom: "4.8rem",
      contentWidth: "60%",
    },
    laptop: {
      paddingTop: "13rem",
      paddingBottom: "3.6rem",
    },
  },
  home: {
    paddingTop: "3rem",
    paddingBottom: "8rem",
    contentMargin: "1.5rem 0 0 0",
    tablet: {
      paddingTop: "15.5rem",
      paddingBottom: "18.4rem",
      contentWidth: "60%",
    },
    laptop: {
      paddingTop: "20.5rem",
      paddingBottom: "23.6rem",
    },
  },
  primary: {
    paddingTop: "6rem",
    paddingBottom: "4rem",
    contentMargin: "3.5rem 0 0 0",
    tablet: {
      paddingTop: "16rem",
      paddingBottom: "16rem",
      contentWidth: "60%",
    },
    laptop: {
      paddingTop: "16rem",
      paddingBottom: "22rem",
    },
  },
  secondary: {
    paddingTop: "6rem",
    paddingBottom: "9rem",
    contentMargin: "6.5rem 0 0 0",
    tablet: {
      paddingTop: "16rem",
      paddingBottom: "16rem",
      contentWidth: "55%",
      contentMargin: "0",
    },
    laptop: {
      paddingTop: "16rem",
      paddingBottom: "22rem",
    },
  },
  noImage: {
    paddingTop: "",
    paddingBottom: "",
    contentMargin: "6.5rem 0 0 0",
    tablet: {
      contentWidth: "80%",
    },
    laptop: {
      paddingTop: "",
      paddingBottom: "",
    },
  },
  skillset: {
    paddingTop: "6rem",
    paddingBottom: "8rem",
    contentMargin: "0 0 6.5rem 0",
    textAlign: "center",
    tablet: {
      paddingTop: "14rem",
      paddingBottom: "16rem",
      contentWidth: "100%",
      contentMargin: "0 0 10rem 0",
      textAlign: "center",
    },
    laptop: {
      paddingTop: "16rem",
      paddingBottom: "22rem",
      contentWidth: "60%",
      contentMargin: "0",
      textAlign: "left",
    },
  },
  centeredNoImage: {
    paddingTop: "16rem",
    paddingBottom: "16rem",
    contentMargin: "0 auto",
    textAlign: "center",
    tablet: {
      paddingTop: "16rem",
      paddingBottom: "16rem",
      textAlign: "center",
    },
    laptop: {
      paddingTop: "26rem",
      paddingBottom: "26rem",
      textAlign: "center",
    },
  },
  halfWidth: {
    paddingTop: "6rem",
    paddingBottom: "8rem",
    tablet: {
      paddingTop: "14rem",
      paddingBottom: "16rem",
      contentWidth: "50%",
      textAlign: "left",
    },
    laptop: {
      paddingTop: "16rem",
      paddingBottom: "22rem",
      contentWidth: "60%",
    },
  },
  tertiary: {
    paddingTop: "6rem",
    paddingBottom: "4rem",
    contentMargin: "0 0 3.5rem 0",
    contentWidth: "34.5rem",
    imageMargin: "0",
    imageMaxWidth: "47.5rem",
    tablet: {
      paddingTop: "14rem",
      paddingBottom: "16rem",
      contentWidth: "38.5rem",
    },
    laptop: {
      paddingTop: "16rem",
      paddingBottom: "22rem",
      contentWidth: "40.6rem",
    },
  },
  quaternary: {
    paddingTop: "6rem",
    paddingBottom: "4rem",
    contentMargin: "0 0 6.5rem 0",
    contentWidth: "34.5rem",
    tablet: {
      paddingTop: "16rem",
      paddingBottom: "12.5rem",
      contentWidth: "38.3rem",
      contentMargin: "0 0 5.5rem 0",
    },
    laptop: {
      paddingTop: "16rem",
      paddingBottom: "16.5rem",
      contentWidth: "60rem",
      contentMargin: "0 0 7rem 0",
    },
  },
  withArrow: {
    paddingTop: "12rem",
    paddingBottom: "16rem",
    contentMargin: "",
    contentWidth: "34.5rem",
    textAlign: "center",
    tablet: {
      paddingTop: "21rem",
      paddingBottom: "16rem",
      contentWidth: "33.4rem",
      contentMargin: "0",
      textAlign: "left",
      height: "20.7rem",
    },
    laptop: {
      paddingTop: "24rem",
      paddingBottom: "16rem",
      contentWidth: "45rem",
      height: "23.1rem",
      contentMargin: "0",
      textAlign: "0",
    },
  },
};
